name: showboxd
description: "Registro de shows"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  permission_handler: ^12.0.1
  firebase_storage: ^13.0.1
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  google_sign_in: ^6.1.0
  google_fonts: ^6.3.2
  platform_file: ^0.1.0
  path_provider: ^2.1.5
  foundation: ^0.0.5
  photo_view: ^0.15.0
  image_picker: ^1.2.0
  gallery_saver_plus: ^3.2.9
  uuid: ^4.5.1
  intl: ^0.20.2
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/google_logo.png
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png" 